export const NEW_CART_ITEM_ADDING = 'NEW_CART_ITEM_ADDING';
export const NEW_CART_ITEM_ADDED = 'NEW_CART_ITEM_ADDED';
export const NEW_CART_ITEM_ADDING_FAILED = 'NEW_CART_ITEM_ADDING_FAILED';
export const NEW_CART_ITEM_RESET = 'NEW_CART_ITEM_RESET';

export const CART_ITEM_REMOVING = 'CART_ITEM_REMOVING';
export const CART_ITEM_REMOVED = 'CART_ITEM_REMOVED';
export const CART_ITEM_REMOVING_FAILED = 'CART_ITEM_REMOVING_FAILED';
