export const FILE_UPLOADING = 'FILE_UPLOADING';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
export const FILE_UPLOAD_RESET = 'FILE_UPLOAD_RESET';
