export const ALL_PRODUCT_LOADING = 'ALL_PRODUCT_LOADING';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_ERROR = 'ALL_PRODUCT_ERROR';

export const TRENDING_PRODUCT_LOADING = 'TRENDING_PRODUCT_LOADING';
export const TRENDING_PRODUCT_SUCCESS = 'TRENDING_PRODUCT_SUCCESS';
export const TRENDING_PRODUCT_ERROR = 'TRENDING_PRODUCT_ERROR';

export const SUNGLASSES_LOADING = 'SUNGLASSES_LOADING';
export const SUNGLASSES_SUCCESS = 'SUNGLASSES_SUCCESS';
export const SUNGLASSES_ERROR = 'SUNGLASSES_ERROR';

export const POWERGLASSES_LOADING = 'POWERGLASSES_LOADING';
export const POWERGLASSES_SUCCESS = 'POWERGLASSES_SUCCESS';
export const POWERGLASSES_ERROR = 'POWERGLASSES_ERROR';

export const CONTACT_LENSES_LOADING = 'CONTACT_LENSES_LOADING';
export const CONTACT_LENSES_SUCCESS = 'CONTACT_LENSES_SUCCESS';
export const CONTACT_LENSES_ERROR = 'CONTACT_LENSES_ERROR';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADDED_PRODUCT_RESET = 'ADDED_PRODUCT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
