export const ALL_PRODUCT_LOADING = 'ALL_PRODUCT_LOADING';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_ERROR = 'ALL_PRODUCT_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
