export const ALL_PRODUCT_LOADING = 'ALL_PRODUCT_LOADING';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_ERROR = 'ALL_PRODUCT_ERROR';

export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const ADDED_PRODUCT_RESET = 'ADDED_PRODUCT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
