export const FETCH_THEME_LOADING = 'FETCH_THEME_LOADING';
export const FETCH_THEME_SUCCESS = 'FETCH_THEME_SUCCESS';
export const FETCH_THEME_ERROR = 'FETCH_THEME_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
